const STORAGE_KEY = 'personal-planner-tasks-v1';
const $ = (id) => document.getElementById(id);
const state = { selectedDate: startOfDay(new Date()), weekStart: mondayOf(new Date()), view: 'today' };

function startOfDay(date) { const value = new Date(date); value.setHours(0, 0, 0, 0); return value; }
function mondayOf(date) { const value = startOfDay(date); value.setDate(value.getDate() - ((value.getDay() + 6) % 7)); return value; }
function toKey(date) { const value = new Date(date); return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, '0')}-${String(value.getDate()).padStart(2, '0')}`; }
function fromKey(key) { return new Date(`${key}T00:00:00`); }
function addDays(date, days) { const value = new Date(date); value.setDate(value.getDate() + days); return value; }
function formatDate(date, options) { return new Intl.DateTimeFormat('vi-VN', options).format(date); }
function getTasks() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || [] } catch { return [] } }
function saveTasks(tasks) { localStorage.setItem(STORAGE_KEY, JSON.stringify(tasks)); }
function taskDate(task) { return fromKey(task.date); }
function taskTime(task) { return task.allDay ? 'Cả ngày' : task.time || 'Chưa đặt giờ'; }
function seed() { if (getTasks().length) return; const today = toKey(new Date()); saveTasks([{ id: crypto.randomUUID(), title: 'Chuẩn bị proposal dự án', notes: '', date: today, time: '09:00', allDay: false, priority: 'high', done: false }, { id: crypto.randomUUID(), title: 'Gọi trao đổi với nhà cung cấp', notes: '', date: today, time: '14:00', allDay: false, priority: 'medium', done: false }, { id: crypto.randomUUID(), title: 'Rà soát kế hoạch tuần', notes: '', date: today, time: '', allDay: true, priority: 'low', done: false }]); }
function sameDay(a, b) { return toKey(a) === toKey(b); }
function sorted(tasks) { return [...tasks].sort((a, b) => Number(a.done) - Number(b.done) || a.date.localeCompare(b.date) || (a.time || '99:99').localeCompare(b.time || '99:99')); }
function renderTask(task) { const el = document.createElement('article'); el.className = `task ${task.priority} ${task.done ? 'completed' : ''}`; el.innerHTML = `<div class="task-body"><div class="task-title"></div><div class="task-meta"></div></div><input class="check" type="checkbox" aria-label="Đánh dấu hoàn thành" ${task.done ? 'checked' : ''}>`; el.querySelector('.task-title').textContent = task.title; el.querySelector('.task-meta').textContent = taskTime(task); el.addEventListener('click', event => { if (event.target.classList.contains('check')) return; openDialog(task) }); el.querySelector('.check').addEventListener('change', event => { const tasks = getTasks().map(item => item.id === task.id ? { ...item, done: event.target.checked } : item); saveTasks(tasks); render() }); return el; }
function placeTasks(container, tasks, message) { container.replaceChildren(); if (!tasks.length) { container.innerHTML = `<p class="empty">${message}</p>`; return } tasks.forEach(task => container.append(renderTask(task))); }
function renderDateStrip() { const strip = $('date-strip'); strip.replaceChildren(); for (let i = -3; i <= 3; i++) { const date = addDays(state.selectedDate, i); const cell = document.createElement('button'); cell.className = `date-cell ${sameDay(date, state.selectedDate) ? 'selected' : ''}`; cell.innerHTML = `${formatDate(date, { weekday: 'short' }).replace('.', '')}<b>${date.getDate()}</b>`; if (getTasks().some(task => task.date === toKey(date) && !task.done)) cell.innerHTML += '<span class="marker"></span>'; cell.addEventListener('click', () => { state.selectedDate = date; state.weekStart = mondayOf(date); render() }); strip.append(cell) } }
function renderToday() { const tasks = sorted(getTasks().filter(task => task.date === toKey(state.selectedDate))); const open = tasks.filter(task => !task.done), done = tasks.filter(task => task.done); $('eyebrow').textContent = sameDay(state.selectedDate, new Date()) ? 'Hôm nay' : formatDate(state.selectedDate, { weekday: 'long' }); $('page-title').textContent = formatDate(state.selectedDate, { day: 'numeric', month: 'long' }); $('open-count').textContent = `${open.length} việc`; $('done-count').textContent = `${done.length} việc`; renderDateStrip(); placeTasks($('today-tasks'), open, 'Chưa có việc cần làm.'); placeTasks($('done-tasks'), done, 'Chưa có việc hoàn thành.'); }
function renderCalendar() { const header = $('week-calendar'); header.replaceChildren(); const blank = document.createElement('div'); header.append(blank); for (let d = 0; d < 7; d++) { const date = addDays(state.weekStart, d); const cell = document.createElement('div'); cell.className = 'day-label'; cell.innerHTML = `${formatDate(date, { weekday: 'short' }).replace('.', '')}<br><b>${date.getDate()}</b>`; header.append(cell) }; for (const hour of [8, 9, 10, 11, 12, 13, 14, 15, 16, 17]) { const hourLabel = document.createElement('div'); hourLabel.className = 'hour'; hourLabel.textContent = `${String(hour).padStart(2, '0')}:00`; header.append(hourLabel); for (let d = 0; d < 7; d++) { const date = addDays(state.weekStart, d), cell = document.createElement('div'); getTasks().filter(task => task.date === toKey(date) && !task.allDay && Number((task.time || '99:00').slice(0, 2)) === hour).forEach(task => { const event = document.createElement('div'); event.className = `calendar-event ${task.priority}`; event.textContent = task.title; event.onclick = () => openDialog(task); cell.append(event) }); header.append(cell) } } $('week-label').textContent = `${formatDate(state.weekStart, { day: 'numeric', month: 'short' })} – ${formatDate(addDays(state.weekStart, 6), { day: 'numeric', month: 'short' })}`; }
function renderAll() {
  const container = $('all-tasks'), tasks = sorted(getTasks());
  container.replaceChildren();
  if (!tasks.length) { container.innerHTML = '<p class="empty">Chưa có công việc nào.</p>'; return; }
  const groups = tasks.reduce((result, task) => { (result[task.date] ||= []).push(task); return result; }, {});
  Object.entries(groups).forEach(([date, dayTasks]) => {
    const group = document.createElement('section'); group.className = 'task-day';
    const dateValue = fromKey(date), heading = document.createElement('div'); heading.className = 'task-day-heading';
    heading.innerHTML = `<h3>${sameDay(dateValue, new Date()) ? 'Hôm nay' : formatDate(dateValue, { weekday: 'long', day: 'numeric', month: 'long' })}</h3><span>${dayTasks.length} việc</span>`;
    const list = document.createElement('div'); list.className = 'task-list'; dayTasks.forEach(task => list.append(renderTask(task)));
    group.append(heading, list); container.append(group);
  });
}
function render() { renderToday(); renderCalendar(); renderAll(); document.querySelectorAll('.view').forEach(el => el.classList.toggle('active', el.id === `${state.view}-view`)); document.querySelectorAll('.bottom-nav button').forEach(el => el.classList.toggle('active', el.dataset.view === state.view)); }
function openDialog(task) { const form = $('task-form'); form.reset(); $('dialog-title').textContent = task ? 'Chỉnh sửa công việc' : 'Thêm công việc'; $('task-id').value = task?.id || ''; $('task-title').value = task?.title || ''; $('task-notes').value = task?.notes || ''; $('task-date').value = task?.date || toKey(state.selectedDate); $('task-time').value = task?.time || ''; $('all-day').checked = task?.allDay || false; $('task-priority').value = task?.priority || 'medium'; $('delete-task').classList.toggle('hidden', !task); $('task-dialog').showModal(); }
$('add-button').onclick = () => openDialog(); $('close-dialog').onclick = () => $('task-dialog').close(); $('today-button').onclick = () => { state.selectedDate = startOfDay(new Date()); state.weekStart = mondayOf(new Date()); state.view = 'today'; render() }; $('previous-week').onclick = () => { state.weekStart = addDays(state.weekStart, -7); renderCalendar() }; $('next-week').onclick = () => { state.weekStart = addDays(state.weekStart, 7); renderCalendar() }; document.querySelectorAll('.bottom-nav button').forEach(button => button.onclick = () => { state.view = button.dataset.view; render() }); $('clear-completed').onclick = () => { saveTasks(getTasks().filter(task => !task.done)); render() }; $('delete-task').onclick = () => { saveTasks(getTasks().filter(task => task.id !== $('task-id').value)); $('task-dialog').close(); render() }; $('task-form').onsubmit = (event) => { event.preventDefault(); const id = $('task-id').value; const task = { id: id || crypto.randomUUID(), title: $('task-title').value.trim(), notes: $('task-notes').value.trim(), date: $('task-date').value, time: $('task-time').value, allDay: $('all-day').checked, priority: $('task-priority').value, done: id ? getTasks().find(item => item.id === id)?.done : false }; const tasks = getTasks(); saveTasks(id ? tasks.map(item => item.id === id ? task : item) : [...tasks, task]); $('task-dialog').close(); state.selectedDate = fromKey(task.date); state.weekStart = mondayOf(state.selectedDate); render() };
let swipeStartX = 0;
$('date-strip').addEventListener('touchstart', event => { swipeStartX = event.touches[0].clientX; }, { passive: true });
$('date-strip').addEventListener('touchend', event => { const delta = event.changedTouches[0].clientX - swipeStartX; if (Math.abs(delta) < 45) return; state.selectedDate = addDays(state.selectedDate, delta < 0 ? 1 : -1); state.weekStart = mondayOf(state.selectedDate); render(); }, { passive: true });
seed(); render();
